#!/usr/bin/env python3
"""Build runtime.lib, libc.lib, and monolithic .rel files from split modules.

Usage:
    python lib/build_libs.py          # build both
    python lib/build_libs.py runtime   # build runtime.lib only
    python lib/build_libs.py libc      # build libc.lib only
"""
import os
import re
import sys
import subprocess
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RT_DIR = os.path.join(SCRIPT_DIR, "rt")
LC_DIR = os.path.join(SCRIPT_DIR, "lc")

def run(cmd, **kwargs):
    """Run a command, returning (success, output)."""
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    output = result.stdout + result.stderr
    return result.returncode == 0, output

def assemble_dir(src_dir, verbose=True):
    """Assemble all .mac files in a directory to .rel files."""
    mac_files = sorted(glob.glob(os.path.join(src_dir, "*.mac")))
    if not mac_files:
        print(f"  No .mac files found in {src_dir}")
        return False

    all_ok = True
    for mac_file in mac_files:
        rel_file = mac_file.replace(".mac", ".rel")
        name = os.path.basename(mac_file)
        ok, output = run(["um80", mac_file, "-o", rel_file])
        if not ok:
            print(f"  FAIL: {name}")
            for line in output.strip().split("\n"):
                if "Error" in line:
                    print(f"    {line}")
            all_ok = False
        elif verbose:
            # Extract code/data sizes from output
            for line in output.strip().split("\n"):
                if "Code segment:" in line or "Data segment:" in line:
                    pass  # quiet
            print(f"  OK: {name}")
    return all_ok

def build_lib(lib_path, rel_dir):
    """Create a .lib archive from all .rel files in a directory."""
    rel_files = sorted(glob.glob(os.path.join(rel_dir, "*.rel")))
    if not rel_files:
        print(f"  No .rel files found in {rel_dir}")
        return False

    # Remove old lib first
    if os.path.exists(lib_path):
        os.remove(lib_path)

    cmd = ["ulib80", "-c", lib_path] + rel_files
    ok, output = run(cmd)
    if ok:
        print(f"  Created {os.path.basename(lib_path)}")
        for line in output.strip().split("\n"):
            if "Modules:" in line or "Symbols:" in line:
                print(f"    {line.strip()}")
    else:
        print(f"  FAIL creating {os.path.basename(lib_path)}")
        print(output)
    return ok

# Standard EQU symbols present in most modules - emitted once in concat header
SHARED_EQUS = {'BDOS', 'CONOUT', 'CONIN', 'PRTSTR'}

def concat_modules(src_dir, output_path, header_comment):
    """Concatenate modules into a single .mac file for peephole optimization.

    Strips per-module boilerplate (.Z80, END, shared EQUs) and removes
    EXTRN declarations for symbols defined (PUBLIC) within the concat.
    Emits CSEG before each module so segment state is predictable.
    Lines containing ;! are excluded from the concat output.
    """
    mac_files = sorted(glob.glob(os.path.join(src_dir, "*.mac")))
    if not mac_files:
        print(f"  No .mac files in {src_dir}")
        return False

    # First pass: collect all PUBLIC symbols
    public_syms = set()
    for path in mac_files:
        with open(path) as f:
            for line in f:
                m = re.match(r'\s+PUBLIC\s+(\S+)', line)
                if m:
                    public_syms.add(m.group(1))

    # Second pass: build concatenated output
    out = []
    out.append(f'; {os.path.basename(output_path)} - generated by build_libs.py from {os.path.basename(src_dir)}/ modules')
    out.append('; DO NOT EDIT - edit the individual module files instead')
    out.append('')
    out.append('\t.Z80')
    out.append('')
    out.append('; CP/M BDOS function numbers')
    out.append('BDOS\tEQU\t5\t\t; BDOS entry point')
    out.append('CONOUT\tEQU\t2\t\t; Console output (char in E)')
    out.append('CONIN\tEQU\t1\t\t; Console input (char returned in A)')
    out.append('PRTSTR\tEQU\t9\t\t; Print string (address in DE, \'$\' terminated)')
    out.append('')
    out.append('\tCSEG')

    for path in mac_files:
        name = os.path.basename(path)
        with open(path) as f:
            lines = f.read().splitlines()

        out.append('')
        out.append(f'; {"=" * 60}')
        out.append(f'; {name}')
        out.append(f'; {"=" * 60}')
        out.append('\tCSEG')

        for line in lines:
            # Skip lines with ;! marker
            if ';!' in line:
                continue
            # Skip .Z80
            if re.match(r'\s*\.Z80\s*$', line):
                continue
            # Skip END
            if re.match(r'\s+END\s*$', line):
                continue
            # Skip shared EQU definitions
            m = re.match(r'(\w+)\s+EQU\s+', line)
            if m and m.group(1) in SHARED_EQUS:
                continue
            # Skip "; CP/M BDOS function numbers" comment
            if re.match(r'^;\s*CP/M BDOS function numbers', line):
                continue
            # Skip EXTRN for symbols defined within the concat
            m = re.match(r'\s+EXTRN\s+(\S+)', line)
            if m and m.group(1) in public_syms:
                continue
            out.append(line)

    out.append('')
    out.append('\tEND')
    out.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(out))

    print(f"  Generated {os.path.basename(output_path)} ({len(mac_files)} modules)")
    return True

def build_runtime():
    """Build runtime.lib and runtime.rel from lib/rt/ modules."""
    print("Building runtime...")
    print("  Assembling modules...")
    if not assemble_dir(RT_DIR):
        print("  Assembly errors - fix before building library")
        return False
    ok = build_lib(os.path.join(SCRIPT_DIR, "runtime.lib"), RT_DIR)

    # Build monolithic .mac and .rel
    mac_path = os.path.join(SCRIPT_DIR, "runtime.mac")
    rel_path = os.path.join(SCRIPT_DIR, "runtime.rel")
    if not concat_modules(RT_DIR, mac_path, "runtime"):
        return False
    success, output = run(["um80", mac_path, "-o", rel_path])
    if success:
        print(f"  Assembled runtime.rel")
    else:
        print(f"  FAIL assembling runtime.mac")
        print(output)
        return False
    return ok

def build_libc():
    """Build libc.lib and libc.rel from lib/lc/ modules."""
    print("Building libc...")
    print("  Assembling modules...")
    if not assemble_dir(LC_DIR):
        print("  Assembly errors - fix before building library")
        return False
    ok = build_lib(os.path.join(SCRIPT_DIR, "libc.lib"), LC_DIR)

    # Build monolithic .mac and .rel
    mac_path = os.path.join(SCRIPT_DIR, "libc.mac")
    rel_path = os.path.join(SCRIPT_DIR, "libc.rel")
    if not concat_modules(LC_DIR, mac_path, "libc"):
        return False
    success, output = run(["um80", mac_path, "-o", rel_path])
    if success:
        print(f"  Assembled libc.rel")
    else:
        print(f"  FAIL assembling libc.mac")
        print(output)
        return False
    return ok

def main():
    targets = sys.argv[1:] if len(sys.argv) > 1 else ["runtime", "libc"]
    ok = True
    for target in targets:
        if target == "runtime":
            ok = build_runtime() and ok
        elif target == "libc":
            ok = build_libc() and ok
        else:
            print(f"Unknown target: {target}")
            ok = False
    if not ok:
        sys.exit(1)
    print("\nBuild complete.")

if __name__ == "__main__":
    main()
