; Exact copy of hello3.mac with all indexing and _putchar
	.Z80

	PUBLIC	_main
	EXTRN	_putchar

	CSEG

_main:
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	HL,-4
	ADD	HL,SP
	LD	SP,HL
	LD	HL,@STR1
	LD	(IX-2),L
	LD	(IX-1),H
	LD	HL,0
	LD	(IX-4),L
	LD	(IX-3),H
@WHILE1:
	; First s[i] computation for condition
	LD	L,(IX-4)
	LD	H,(IX-3)
	PUSH	HL
	LD	L,(IX-2)
	LD	H,(IX-1)
	POP	DE
	ADD	HL,DE
	LD	L,(HL)
	LD	H,0
	LD	A,H
	OR	L
	JP	Z,@ENDWHILE2

	; Second s[i] computation for putchar arg
	LD	L,(IX-4)
	LD	H,(IX-3)
	PUSH	HL
	LD	L,(IX-2)
	LD	H,(IX-1)
	POP	DE
	ADD	HL,DE
	LD	L,(HL)
	LD	H,0

	; Call putchar
	PUSH	HL
	CALL	_putchar
	POP	DE

	; Increment i
	LD	L,(IX-4)
	LD	H,(IX-3)
	EX	DE,HL
	LD	HL,1
	ADD	HL,DE
	LD	(IX-4),L
	LD	(IX-3),H
	JP	@WHILE1
@ENDWHILE2:
	LD	HL,0
	JP	@main_ret
@main_ret:
	LD	SP,IX
	POP	IX
	RET


	DSEG
@STR1:
	DB	'Hi',0DH,'',0AH,'',0

	END
