; lc_printf_llu.mac - printf %llu handler (unsigned long long decimal)
	.Z80

	EXTRN	_printf_loop
	EXTRN	_prt_dec32

	CSEG

	PUBLIC	__printf_handle_llu
__printf_handle_llu:
	PUSH	HL
	LD	H,0
	LD	L,C
	PUSH	BC
	PUSH	IX
	POP	DE
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	EX	DE,HL
	CALL	_prt_dec32
	POP	BC
	LD	A,C
	ADD	A,8
	LD	C,A
	POP	HL
	JP	_printf_loop

	END
